spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test
    driver_class_name: com.mysql.jdbc.Driver
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test
      repositories:
        enabled: true